// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Outspire",
    platforms: [
        .iOS("17.0") // ActivityKit requires iOS 16.1 or later
    ],
    products: [
        .iOSApplication(
            name: "Outspire",
            targets: ["AppModule", "ClassActivityExtension"], // Add the widget extension target
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .appTransportSecurity(configuration: .init(
                    exceptionDomains: [
                        .init(
                            domainName: "101.230.1.173",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        )
                    ]
                )),
                .faceID(purposeString: "Required to protect sensitive privacy, including academic score, etc."),
                .backgroundModes(["remote-notification"]),
                .pushNotifications(),
                .liveActivity() // Add Live Activity capability
            ],
            appCategory: .education
        ),
        .widgetExtension(
            name: "ClassActivityExtension",
            targets: ["ClassActivityExtension"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/scinfu/SwiftSoup.git", "2.7.6"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftSoup", package: "SwiftSoup"),
                "ClassActivityModule" // Add dependency on our shared module
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        ),
        .target(
            name: "ClassActivityModule",
            path: "ClassActivityModule"
        ),
        .widgetTarget(
            name: "ClassActivityExtension",
            dependencies: ["ClassActivityModule"],
            path: "ClassActivityExtension"
        )
    ]
)